# Generated by Django 5.2.4 on 2025-11-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_monthlyattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyattendance',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyattendance',
            unique_together=set(),
        ),
    ]
