# Generated by Django 5.2.4 on 2025-11-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_monthlyattendance_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='',
        ),
    ]
